markdown: kramdown

remote_theme: hydecorp/hydejack

lang:                  en
title:                 Coral Kashri

menu:
  - title:             About
    url:               /
  - title:             C++ Senioreas Articles List
    url:               /blog/Cpp-Senioreas-All-Articles/
  - title:             CoreC++ 2023 Talks' slides
    url:               /talks/from-a-modern-to-an-unbelievably-modern-cpp/
  - title:             C++ Senioreas Blog
    url:               https://cppsenioreas.wordpress.com

accent_color: rgb(79,177,186)

author:
  name:  Coral Kashri
  email: coralkashri@gmail.com
  about: |
    Senior C++ developer
    Writer of C++ Senioreas blog
  social:
    twitter: koralkashri
    github:  coralkashri
    email: coralkashri@gmail.com
    rss: https://cppsenioreas.wordpress.com/feed/
    # linkedin: coral-kashri-330b41162
    # reddit: CoralKashri
