name: Latest C++ Senioreas blog posts
on:
  push:
    branches:
      - master
  schedule:
    # Runs every day at 16:00
    - cron: '0 16 */1 * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: "6"
          feed_list: "https://cppsenioreas.wordpress.com/feed/"
          gh_token: ${{ secrets.GH_TOKEN }}
          comment_tag_name: "CPP-SENIOREAS-POSTS"
